# Exclude the docs directory from linting
exclude = ["docs"]

[lint]
# Allow longer line length for specific paths
line-length = 88

[lint.per-file-ignores]
# Allow long lines in test files
"tests/*" = ["E501"]