# Exclude the docs directory from linting
exclude = ["docs"]

# Allow longer line length for specific paths
[lint]
line-length = 88

[lint.per-file-ignores]
# Allow long lines in test files
"tests/*" = ["E501"]